# Obtener todas las comisarías
GET http://localhost:3001/comisarias

# Obtener una comisaría por ID
GET http://localhost:3001/comisarias/2

# Crear una comisaría nueva
POST http://localhost:3001/comisarias
Content-Type: application/json

{
  "nombre": "",
  "direccion": "",
  "telefono": ""
}

# Actualizar una comisaría existente
PUT http://localhost:3001/comisarias/
Content-Type: application/json

{
  "nombre": "",
  "direccion": "",
  "telefono": ""
}

# Eliminar una comisaría por ID
DELETE http://localhost:3001/comisarias/   